name: CD Pipeline
# Only trigger, when the build workflow succeeded i.e. CI Pipelne
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/bike_sharing_api:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f bike_sharing_api || true

      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 80:8001 --name bike_sharing_api $DOCKER_USER/bike_sharing_api:latest
