name: Model Training & Deployment Pipeline

on:
  push:
    branches:
      - main 
  workflow_dispatch:  

jobs:

  setup:
    name: Setup & Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # - name: Cache Dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements/requirements.txt

      - name: Upload Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: python-dependencies
          path: ~/.cache/pip

  train_model:
    name: Train Model
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        uses: actions/download-artifact@v4
        with:
          name: python-dependencies
          path: ~/.cache/pip

      - name: Install Dependencies (Ensure Installation)
        run: pip install -r requirements/requirements.txt

      - name: Train Model
        run: |
          python bikeshare_model/train_pipeline.py
          python bikeshare_model/predict.py

      - name: Save Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: bikeshare_model/trained_models/